pipeline {
    agent any

    environment{
        JAVA_HOME = tool name: 'Java 8_152'
    }

    stages {
        stage('Preparation') {
            steps {
                echo "${JAVA_HOME}"
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.6.0-jdk-8-alpine'
                    reuseNode true
                }
            }
            steps {
                echo 'Starting Build stage...'
                configFileProvider([configFile(fileId: 'byggReleaseConfig', variable: 'MAVEN_SETTINGS')]) {
                    sh 'pwd'
                    echo 'Compiling, testing and building...'
                    sh 'mvn --global-settings ${MAVEN_SETTINGS} clean install'
                }
            }     
        }        
    }

    post {
        success {
            echo 'Build succeeded'
        }

        always {
            echo 'Starting results handling...'
            junit '**/target/surefire-reports/TEST-*.xml'
            jacoco()
            archiveArtifacts '**/target/*.jar'

            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}