pipeline {
    agent any
//TEST webhook
    stages {

        stage('Build') {
            agent {
                docker {
                    image 'maven:3.6.0-jdk-8-alpine'
                    reuseNode true
                }
            }
            steps{
                echo 'Starting Build stage...'
                configFileProvider([configFile(fileId: 'byggReleaseConfig', variable: 'MAVEN_SETTINGS')]) {
                    sh 'pwd'
                    echo 'Compiling, testing and building...'
                    sh 'mvn --global-settings ${MAVEN_SETTINGS} -P test-coverage clean install'
                }
            }     
        }
        
        stage('Results'){
            steps{
                echo 'Starting Results stage...'
                junit '**/target/surefire-reports/TEST-*.xml'
                archiveArtifacts '**/target/*.jar'
                archiveArtifacts '**/target/*.zip'     
            }
        }
        
    }

    post { 
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}